services:
  db:
    image: postgres:16-alpine
    container_name: binance_postgres
    restart: always
    environment:
      - POSTGRES_USER=bindatacoll
      - POSTGRES_PASSWORD=dt_hfgd_yyyd
      - POSTGRES_DB=market_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-config/custom.conf:/etc/postgresql/postgresql.conf # <-- конфигурация параметров работы postgresql
  seq:
    image: datalust/seq:latest # Официальный образ Seq
    container_name: binance_seq
    restart: always
    environment:
      - ACCEPT_EULA=Y # Обязательно для принятия лицензионного соглашения
    ports:
      - "5341:80"     # Веб-интерфейс будет доступен на порту 5341
      - "5342:5341"   # Порт для приема логов (опционально, если нужно снаружи)
    volumes:
      - seq_data:/data # Сохраняем данные и настройки Seq
#  app:
#    image: ghcr.io/alexpaturov/binancedatacollector/binance-collector:latest
#    container_name: binance_collector_app
#    restart: always
#    depends_on:
#      - db
#      - seq # <-- Зависимость от Seq
#      - rabbitmq
#    ports:
#      - "7001:7001" # Пробрасываем порт 7001 хост-машины на порт 7001 контейнера
#    environment:
#      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=market_analytics;Username=bindatacoll;Password=dt_hfgd_yyyd
#      - ConnectionStrings__HangfireConnection=Host=db;Port=5432;Database=market_analytics_jobs;Username=bindatacoll;Password=dt_hfgd_yyyd
#      - SEQ_URL=http://seq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Порт для подключения клиентов
      - "15672:15672" # Порт для веб-интерфейса управления
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest # Имя пользователя для админки и подключения
      - RABBITMQ_DEFAULT_PASS=guest
volumes:     # <-- Определяем тома
  postgres_data:
  seq_data:   
  rabbitmq_data: