services:
  db: # Дополняем сервис db
    ports:
      - "5432:5432" # Открываем порт для DBeaver

  seq: # Дополняем сервис seq
    ports:
      - "5341:80" # Открываем порт для UI

  rabbitmq: # Дополняем сервис rabbitmq
    ports:
      - "5672:5672"   # Порт для подключения
      - "15672:15672" # Порт для UI

  worker: # Добавляем сервис worker
    build:
      context: .
      dockerfile: src/BinanceDataCollector.Worker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started # У RabbitMQ нет healthcheck по умолчанию, ждем старта
    ports:
      - "7001:7001" # Для дашборда Hangfire
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=market_analytics;Username=bindatacoll;Password=dt_hfgd_yyyd
      - ConnectionStrings__HangfireConnection=Host=db;Port=5432;Database=market_analytics_jobs;Username=bindatacoll;Password=dt_hfgd_yyyd
      - RabbitMQ__HostName=rabbitmq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq

  datamanager: # Добавляем сервис datamanager
    build:
      context: .
      dockerfile: src/BinanceDataCollector.DataManager/Dockerfile
    depends_on:
      - db
      - rabbitmq
    ports:
      - "7002:7002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=market_analytics;Username=bindatacoll;Password=dt_hfgd_yyyd
      - RabbitMQ__HostName=rabbitmq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq