services:
  db:
    image: postgres:16-alpine
    container_name: binance_postgres
    restart: always
    environment:
      - POSTGRES_USER=bindatacoll
      - POSTGRES_PASSWORD=dt_hfgd_yyyd
      - POSTGRES_DB=market_analytics
      - POSTGRES_INITDB_ARGS=--auth-host=md5
      - POSTGRES_HOST_AUTH_METHOD=md5 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5433:5432"
    command:
      - "postgres"
      - "-c"
      - "password_encryption=md5"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bindatacoll -d market_analytics" ]
      interval: 5s
      timeout: 5s
      retries: 5
  pgbouncer:
    image: edoburu/pgbouncer
    container_name: binance_pgbouncer
    restart: always
    depends_on:
      - db
    ports:
      - "6432:5432"
    environment:
      - DB_USER=bindatacoll
      - DB_PASSWORD=dt_hfgd_yyyd
      - DB_HOST=db
      - DB_PORT=5432
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=100
      - MIN_POOL_SIZE=10
      - RESERVE_POOL_SIZE=10
      - AUTH_TYPE=md5
  seq:
    image: datalust/seq:latest # Официальный образ Seq
    container_name: binance_seq
    restart: always
    environment:
      - ACCEPT_EULA=Y # Обязательно для принятия лицензионного соглашения
      - SEQ_FIRSTRUN_ADMINUSERNAME=lex
      - SEQ_FIRSTRUN_ADMINPASSWORD=lex
    ports:
      - "5341:80"     # Веб-интерфейс будет доступен на порту 5341
      - "5342:5341"   # Порт для приема логов (опционально, если нужно снаружи)
    volumes:
      - seq_data:/data # Сохраняем данные и настройки Seq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: binance_rabbitmq
    ports:
      - "5672:5672"   # Порт для подключения клиентов
      - "15672:15672" # Порт для веб-интерфейса управления
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest # Имя пользователя для админки и подключения
      - RABBITMQ_DEFAULT_PASS=guest
volumes:     # <-- Определяем тома
  postgres_data:
  seq_data:   
  rabbitmq_data: