services:
  db:
    image: postgres:16-alpine
    container_name: binance_postgres
    restart: always
    environment:
      - POSTGRES_USER=bindatacoll
      - POSTGRES_PASSWORD=dt_hfgd_yyyd
      - POSTGRES_DB=market_analytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  pgbouncer:
    image: pgbouncer/pgbouncer
    container_name: binance_pgbouncer
    restart: always
    depends_on:
      - db # Запускаться только после базы
    ports:
      - "6432:5432" # А вот он ВЫСТАВЛЯЕТ порт 5432 наружу
    environment:
      - DATABASES_HOST=db
      - DATABASES_PORT=5432
      - DATABASES_USER=bindatacoll
      - DATABASES_PASS=dt_hfgd_yyyd # Твой пароль
      - DATABASES_DB=market_analytics,market_analytics_jobs
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=100
  seq:
    image: datalust/seq:latest # Официальный образ Seq
    container_name: binance_seq
    restart: always
    environment:
      - ACCEPT_EULA=Y # Обязательно для принятия лицензионного соглашения
      - SEQ_FIRSTRUN_ADMIN_USERNAME=lex
      - SEQ_FIRSTRUN_ADMINPASSWORD=seq_lex132&
    ports:
      - "5341:80"     # Веб-интерфейс будет доступен на порту 5341
      - "5342:5341"   # Порт для приема логов (опционально, если нужно снаружи)
    volumes:
      - seq_data:/data # Сохраняем данные и настройки Seq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: binance_rabbitmq
    ports:
      - "5672:5672"   # Порт для подключения клиентов
      - "15672:15672" # Порт для веб-интерфейса управления
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest # Имя пользователя для админки и подключения
      - RABBITMQ_DEFAULT_PASS=guest
volumes:     # <-- Определяем тома
  postgres_data:
  seq_data:   
  rabbitmq_data: