# --- СЕТИ ---
# Объявляем сети, которые будут использовать наши сервисы.
# 'internal_network' - для связи между сервисами, полностью изолирована от внешнего мира.
# 'web' - для связи с обратным прокси Traefik.
networks:
  web:
    name: binancecollector_web
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  internal_network:
    driver: bridge

services:
  # --- ОБРАТНЫЙ ПРОКСИ ---
  # Единая точка входа для всего трафика. Управляет SSL и маршрутизацией.
  traefik:
    image: traefik:v2.10
    container_name: traefik
    hostname: traefik
    restart: always
    command:
      - "--api.insecure=true" # Включаем дашборд (для отладки)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # Явно указываем, какие сервисы выставлять наружу
      - "--entrypoints.web.address=:80" # Открываем порт 80
      - "--entrypoints.websecure.address=:443" # --- Здесь будут настройки для SSL, когда мы их добавим ---
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}" # Передается из Secrets
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--accesslog=true" # Включаем логи
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Дашборд будет доступен на порту 8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Traefik читает метаданные Docker
      - "letsencrypt_data:/letsencrypt"
    networks:
      web:
        ipv4_address: 172.28.0.10

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: binance_tunnel
    restart: always
    command: tunnel run --protocol http2
    environment:
      - TUNNEL_TOKEN=eyJhIjoiY2JjY2Q0MDcyMTA5M2FmNjYxZGIxNDc4NmY0Y2M3M2YiLCJ0IjoiZDM2ZGE1YjQtYTgwOS00MWVhLWJhYmMtNGJlZTU3NWE5N2NhIiwicyI6ImxxYmhXbHNFeHpGT0ZWM1ZTNnJ2K0tiempLRko5TnphUXNNbWh6eGtuT1U9In0=
    networks:
      - web
    depends_on:
      - traefik

  # --- БАЗА ДАННЫХ ---
  db:
    image: postgres:16-alpine
    container_name: binance_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=market_analytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "password_encryption=md5"
    networks:
      - internal_network # База данных подключена ТОЛЬКО к внутренней сети
    ports:
      - "100.96.120.16:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d market_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- СЕРВЕР ЛОГОВ ---
  seq:
    image: datalust/seq:latest
    container_name: binance_seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=${SEQ_ADMIN_USER}
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_ADMIN_PASS}
    volumes:
      - seq_data:/data
    networks:
      - internal_network # Seq доступен только из внутренней сети...
      - web              # ...и через Traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=binancecollector_web"
      - "traefik.http.routers.seq.rule=Host(`seq.jahasim.com`)"
      - "traefik.http.routers.seq.entrypoints=web"
      - "traefik.http.services.seq.loadbalancer.server.port=80"

  # --- БРОКЕР СООБЩЕНИЙ ---
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: binance_rabbitmq
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - internal_network
    # UI RabbitMQ не будем выставлять наружу для безопасности

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: binance_pgbouncer
    restart: always
    depends_on:
      - db
    networks:
      - internal_network # pgbouncer должен быть только во внутренней сети
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=100
      - MIN_POOL_SIZE=10
      - RESERVE_POOL_SIZE=10
      - AUTH_TYPE=scram-sha-256

  worker:
    image: ghcr.io/alexpaturov/binancedatacollector/worker:latest
    container_name: bdc_worker
    restart: always
    depends_on:
      pgbouncer:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7001 # Слушаем внутри контейнера на всех интерфейсах
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=pgbouncer;Port=5432;Database=market_analytics;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__HangfireConnection=Host=pgbouncer;Port=5432;Database=market_analytics_jobs;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - RabbitMQ__HostName=rabbitmq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    networks:
      - internal_network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=binancecollector_web"
      - "traefik.http.routers.hangfire.rule=Host(`hangfire.jahasim.com`)"
      - "traefik.http.routers.hangfire.entrypoints=web"
      - "traefik.http.services.hangfire.loadbalancer.server.port=7001"

  datamanager:
    image: ghcr.io/alexpaturov/binancedatacollector/datamanager:latest
    container_name: bdc_datamanager
    restart: always
    depends_on:
      - pgbouncer
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=pgbouncer;Port=5432;Database=market_analytics;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__HangfireConnection=Host=pgbouncer;Port=5432;Database=market_analytics_jobs;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - RabbitMQ__HostName=rabbitmq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
    networks:
      - internal_network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=binancecollector_web"
      - "traefik.http.routers.datamanager.rule=Host(`datamanager.jahasim.com`)"
      - "traefik.http.routers.datamanager.entrypoints=web"
      - "traefik.http.services.datamanager.loadbalancer.server.port=7002"

volumes:
  postgres_data:
  seq_data:
  rabbitmq_data:
  letsencrypt_data: