-- Единая помесячная партиционная сетка + ротация по размеру диска.
-- См. docs/adr/0007-size-based-retention-and-unified-partitioning.md
--
-- Что делает:
--   1. Партиционирует Ohlcv_1min, Ohlcv_Features, DataQualityReports, DataQualityFindings
--      по той же помесячной сетке, что и Trades.
--   2. Вводит границу ретенции (начало самой старой партиции Trades) и запрещает
--      создавать партиции ниже неё — этим перекрывается повторная закачка удалённого.
--   3. Заменяет календарную ротацию (13 месяцев) на ротацию по размеру.
--
-- ВАЖНО: скрипт ОТКАЗЫВАЕТСЯ работать, если Ohlcv_1min или Ohlcv_Features непусты —
-- партиционирование заполненной таблицы требует перелива данных, а не пересоздания.
-- Применять до того, как заработает агрегация свечей (Фаза 4).
--
--   psql -U bindatacoll -d market_analytics -f 002_unified_partitioning_and_size_retention.sql

BEGIN;

-- ============================================================================
--  0. Предохранитель
-- ============================================================================

DO $$
DECLARE
    candles  BIGINT;
    features BIGINT;
BEGIN
    SELECT count(*) INTO candles  FROM public."Ohlcv_1min";
    SELECT count(*) INTO features FROM public."Ohlcv_Features";

    IF candles > 0 OR features > 0 THEN
        RAISE EXCEPTION
            'Ohlcv_1min (%) или Ohlcv_Features (%) непусты. Миграция пересоздаёт эти таблицы и потеряет данные. Нужен перелив, а не пересоздание.',
            candles, features;
    END IF;
END $$;

-- ============================================================================
--  1. Ohlcv_1min → партиционированная по OpenTime
-- ============================================================================

DROP TABLE IF EXISTS public."Ohlcv_1min" CASCADE;

CREATE TABLE public."Ohlcv_1min" (
    "Symbol" character varying(20) NOT NULL,
    "OpenTime" bigint NOT NULL,
    "OpenPrice" numeric(18,8) NOT NULL,
    "HighPrice" numeric(18,8) NOT NULL,
    "LowPrice" numeric(18,8) NOT NULL,
    "ClosePrice" numeric(18,8) NOT NULL,
    "Volume" numeric(28,8) NOT NULL,
    "ProcessingStatus" character varying(10) DEFAULT 'new'::character varying NOT NULL,
    CONSTRAINT "PK_Ohlcv_1min" PRIMARY KEY ("Symbol", "OpenTime")
) PARTITION BY RANGE ("OpenTime");

CREATE INDEX "IX_Ohlcv_1min_ProcessingStatus_OpenTime"
    ON public."Ohlcv_1min" USING btree ("ProcessingStatus", "OpenTime");

-- ============================================================================
--  2. Ohlcv_Features → партиционированная по OpenTime
-- ============================================================================

DROP TABLE IF EXISTS public."Ohlcv_Features" CASCADE;

CREATE TABLE public."Ohlcv_Features" (
    "Symbol" character varying(20) NOT NULL,
    "OpenTime" bigint NOT NULL,
    "RSI_14" numeric(10,4),
    "MACD_Signal" numeric(18,8),
    "MACD_Hist" numeric(18,8),
    "MA_1051200" numeric(18,8),
    "MA_201600" numeric(18,8),
    "CVD" numeric(28,8),
    CONSTRAINT "Ohlcv_Features_pkey" PRIMARY KEY ("Symbol", "OpenTime")
) PARTITION BY RANGE ("OpenTime");

-- ============================================================================
--  3. DataQualityReports → партиционированная по PeriodMonth (данные сохраняются)
-- ============================================================================

ALTER TABLE public."DataQualityReports" RENAME TO "DataQualityReports_old";

-- Переименование таблицы не трогает имена её констрейнтов и индексов —
-- они бы столкнулись с именами новой таблицы.
ALTER TABLE public."DataQualityReports_old" RENAME CONSTRAINT "DataQualityReports_pkey" TO "DataQualityReports_old_pkey";
ALTER INDEX public.ix_dqr_symbol_month RENAME TO ix_dqr_symbol_month_old;
ALTER INDEX public.ix_dqr_checked_at   RENAME TO ix_dqr_checked_at_old;
ALTER INDEX public.ix_dqr_status       RENAME TO ix_dqr_status_old;

CREATE TABLE public."DataQualityReports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Symbol" character varying(20) NOT NULL,
    "PeriodMonth" date NOT NULL,
    "TradeCount" bigint DEFAULT 0 NOT NULL,
    "GapCount" integer DEFAULT 0 NOT NULL,
    "InvalidPriceCount" integer DEFAULT 0 NOT NULL,
    "OutlierCount" integer DEFAULT 0 NOT NULL,
    "Status" character varying(10) DEFAULT 'ok'::character varying NOT NULL,
    "CheckedAt" timestamp with time zone DEFAULT now() NOT NULL,
    -- Ключ партиционирования обязан входить в PK
    CONSTRAINT "DataQualityReports_pkey" PRIMARY KEY ("Id", "PeriodMonth")
) PARTITION BY RANGE ("PeriodMonth");

CREATE UNIQUE INDEX ix_dqr_symbol_month
    ON public."DataQualityReports" USING btree ("Symbol", "PeriodMonth");
CREATE INDEX ix_dqr_checked_at
    ON public."DataQualityReports" USING btree ("CheckedAt" DESC);
CREATE INDEX ix_dqr_status
    ON public."DataQualityReports" USING btree ("Status")
    WHERE (("Status")::text <> 'ok'::text);

-- ============================================================================
--  4. DataQualityFindings → партиционированная по PeriodFrom (данные сохраняются)
-- ============================================================================

ALTER TABLE public."DataQualityFindings" RENAME TO "DataQualityFindings_old";

ALTER TABLE public."DataQualityFindings_old" RENAME CONSTRAINT "DataQualityFindings_pkey" TO "DataQualityFindings_old_pkey";
ALTER INDEX public.ix_dqf_checked_at   RENAME TO ix_dqf_checked_at_old;
ALTER INDEX public.ix_dqf_severity     RENAME TO ix_dqf_severity_old;
ALTER INDEX public.ix_dqf_group_symbol RENAME TO ix_dqf_group_symbol_old;

CREATE TABLE public."DataQualityFindings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CheckGroup" character varying(32) NOT NULL,
    "CheckType" character varying(64) NOT NULL,
    "Symbol" character varying(20),
    "PeriodFrom" timestamp with time zone NOT NULL,
    "PeriodTo" timestamp with time zone NOT NULL,
    "Severity" character varying(10) NOT NULL,
    "Count" bigint DEFAULT 0 NOT NULL,
    "Details" jsonb,
    "CheckedAt" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "DataQualityFindings_pkey" PRIMARY KEY ("Id", "PeriodFrom")
) PARTITION BY RANGE ("PeriodFrom");

CREATE INDEX ix_dqf_checked_at
    ON public."DataQualityFindings" USING btree ("CheckedAt" DESC);
CREATE INDEX ix_dqf_severity
    ON public."DataQualityFindings" USING btree ("Severity")
    WHERE (("Severity")::text <> 'ok'::text);
CREATE INDEX ix_dqf_group_symbol
    ON public."DataQualityFindings" USING btree ("CheckGroup", "Symbol");

-- ============================================================================
--  5. Граница ретенции
-- ============================================================================

-- Начало самой старой существующей партиции Trades, в Unix-мс.
-- Отдельно нигде не хранится — выводится из схемы.
CREATE OR REPLACE FUNCTION public.fn_retention_floor_ms() RETURNS bigint
    LANGUAGE sql STABLE
    AS $$
    SELECT COALESCE(
        MIN(
            EXTRACT(EPOCH FROM TO_DATE(
                substring(c.relname FROM 'Trades_(\d{4}_\d{2})'), 'YYYY_MM'
            ))::bigint * 1000
        ),
        0
    )
    FROM pg_inherits i
    JOIN pg_class c ON c.oid = i.inhrelid
    WHERE i.inhparent = 'public."Trades"'::regclass;
$$;

-- ============================================================================
--  6. Создание партиций месяца во ВСЕХ таблицах сразу
-- ============================================================================

CREATE OR REPLACE FUNCTION public.sp_ensure_month_partitions(target_time bigint) RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
    month_start TIMESTAMP;
    month_end   TIMESTAMP;
    suffix      TEXT;
    from_ms     BIGINT;
    to_ms       BIGINT;
    floor_ms    BIGINT;
BEGIN
    month_start := DATE_TRUNC('month', TO_TIMESTAMP(target_time / 1000.0) AT TIME ZONE 'UTC');
    month_end   := month_start + INTERVAL '1 month';
    suffix      := TO_CHAR(month_start, 'YYYY_MM');
    from_ms     := EXTRACT(EPOCH FROM month_start)::BIGINT * 1000;
    to_ms       := EXTRACT(EPOCH FROM month_end)::BIGINT * 1000;

    -- Барьер против повторной закачки удалённого: партицию ниже границы ретенции
    -- создавать нельзя, иначе аудитор/импорт архивов вернут дропнутый месяц обратно.
    floor_ms := public.fn_retention_floor_ms();
    IF floor_ms > 0 AND from_ms < floor_ms THEN
        RAISE NOTICE 'Месяц % ниже границы ретенции (%) — партиции не создаются.',
            suffix, TO_CHAR(TO_TIMESTAMP(floor_ms / 1000.0) AT TIME ZONE 'UTC', 'YYYY-MM');
        RETURN;
    END IF;

    -- Trades / Ohlcv_1min / Ohlcv_Features — ключ BIGINT (Unix-мс)
    IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                   WHERE c.relname = 'Trades_' || suffix AND n.nspname = 'public') THEN
        EXECUTE format('CREATE TABLE public.%I PARTITION OF public."Trades" FOR VALUES FROM (%s) TO (%s)',
                       'Trades_' || suffix, from_ms, to_ms);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                   WHERE c.relname = 'Ohlcv_1min_' || suffix AND n.nspname = 'public') THEN
        EXECUTE format('CREATE TABLE public.%I PARTITION OF public."Ohlcv_1min" FOR VALUES FROM (%s) TO (%s)',
                       'Ohlcv_1min_' || suffix, from_ms, to_ms);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                   WHERE c.relname = 'Ohlcv_Features_' || suffix AND n.nspname = 'public') THEN
        EXECUTE format('CREATE TABLE public.%I PARTITION OF public."Ohlcv_Features" FOR VALUES FROM (%s) TO (%s)',
                       'Ohlcv_Features_' || suffix, from_ms, to_ms);
    END IF;

    -- DataQualityReports — ключ DATE
    IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                   WHERE c.relname = 'DataQualityReports_' || suffix AND n.nspname = 'public') THEN
        EXECUTE format('CREATE TABLE public.%I PARTITION OF public."DataQualityReports" FOR VALUES FROM (%L) TO (%L)',
                       'DataQualityReports_' || suffix, month_start::date, month_end::date);
    END IF;

    -- DataQualityFindings — ключ TIMESTAMPTZ
    IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                   WHERE c.relname = 'DataQualityFindings_' || suffix AND n.nspname = 'public') THEN
        EXECUTE format('CREATE TABLE public.%I PARTITION OF public."DataQualityFindings" FOR VALUES FROM (%L) TO (%L)',
                       'DataQualityFindings_' || suffix,
                       month_start AT TIME ZONE 'UTC', month_end AT TIME ZONE 'UTC');
    END IF;
END;
$$;

-- Обратная совместимость: TradeRepository.BulkInsertAsync зовёт эту процедуру.
CREATE OR REPLACE FUNCTION public.sp_ensure_trades_partition(target_time bigint) RETURNS void
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM public.sp_ensure_month_partitions(target_time);
END;
$$;

-- ============================================================================
--  7. Ротация по размеру
-- ============================================================================

DROP FUNCTION IF EXISTS public.sp_rotate_trades_partition();

-- Суммарный размер всех партиционированных данных (с индексами и TOAST).
CREATE OR REPLACE FUNCTION public.fn_partitioned_size_bytes() RETURNS bigint
    LANGUAGE sql STABLE
    AS $$
    SELECT COALESCE(SUM(pg_total_relation_size(i.inhrelid)), 0)
    FROM pg_inherits i
    WHERE i.inhparent IN (
        'public."Trades"'::regclass,
        'public."Ohlcv_1min"'::regclass,
        'public."Ohlcv_Features"'::regclass,
        'public."DataQualityReports"'::regclass,
        'public."DataQualityFindings"'::regclass
    );
$$;

/*
 * Ротация: пока суммарный размер выше порога — дропаем самый старый месяц
 * во всех таблицах сразу (одной транзакцией). Порог приходит снаружи, из конфига.
 *
 * p_min_months_to_keep — предохранитель от самоуничтожения при ошибочно
 * заниженном пороге: месяцы свежее этого окна не трогаем никогда.
 */
CREATE OR REPLACE FUNCTION public.sp_rotate_partitions(
    p_max_bytes bigint,
    p_min_months_to_keep integer DEFAULT 6
) RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
    current_month TIMESTAMP;
    target_month  TIMESTAMP;
    oldest_suffix TEXT;
    oldest_month  TIMESTAMP;
    keep_before   TIMESTAMP;
    total_bytes   BIGINT;
    new_floor_ms  BIGINT;
    dropped       INT := 0;
BEGIN
    current_month := DATE_TRUNC('month', NOW() AT TIME ZONE 'UTC');
    keep_before   := current_month - (p_min_months_to_keep || ' months')::INTERVAL;

    -- Партиции на текущий и следующий месяц должны существовать заранее.
    FOR target_month IN
        SELECT m FROM generate_series(current_month, current_month + INTERVAL '1 month', INTERVAL '1 month') AS m
    LOOP
        PERFORM public.sp_ensure_month_partitions(
            EXTRACT(EPOCH FROM target_month)::BIGINT * 1000);
    END LOOP;

    LOOP
        total_bytes := public.fn_partitioned_size_bytes();
        EXIT WHEN total_bytes <= p_max_bytes;

        SELECT substring(c.relname FROM 'Trades_(\d{4}_\d{2})')
        INTO oldest_suffix
        FROM pg_inherits i
        JOIN pg_class c ON c.oid = i.inhrelid
        WHERE i.inhparent = 'public."Trades"'::regclass
        ORDER BY substring(c.relname FROM 'Trades_(\d{4}_\d{2})')
        LIMIT 1;

        EXIT WHEN oldest_suffix IS NULL;

        oldest_month := TO_DATE(oldest_suffix, 'YYYY_MM');

        -- Предохранитель: свежие месяцы не режем даже под давлением диска.
        IF oldest_month >= keep_before THEN
            RAISE WARNING
                'Размер % байт выше порога %, но самый старый месяц (%) свежее окна в % мес. Ротация остановлена — нужно расширять диск или поднимать порог.',
                total_bytes, p_max_bytes, oldest_suffix, p_min_months_to_keep;
            EXIT;
        END IF;

        EXECUTE format('DROP TABLE IF EXISTS public.%I', 'Trades_'              || oldest_suffix);
        EXECUTE format('DROP TABLE IF EXISTS public.%I', 'Ohlcv_1min_'          || oldest_suffix);
        EXECUTE format('DROP TABLE IF EXISTS public.%I', 'Ohlcv_Features_'      || oldest_suffix);
        EXECUTE format('DROP TABLE IF EXISTS public.%I', 'DataQualityReports_'  || oldest_suffix);
        EXECUTE format('DROP TABLE IF EXISTS public.%I', 'DataQualityFindings_' || oldest_suffix);

        dropped := dropped + 1;
        RAISE NOTICE 'Ротация: месяц % удалён во всех таблицах (было % байт, порог %).',
            oldest_suffix, total_bytes, p_max_bytes;
    END LOOP;

    -- Аудитор не должен искать дыры в том, чего больше нет.
    IF dropped > 0 THEN
        new_floor_ms := public.fn_retention_floor_ms();

        UPDATE public."HistoricalAudit_Watermarks"
        SET "LastChecked_Timestamp" = new_floor_ms,
            "LastChecked_TradeId"   = 0
        WHERE "LastChecked_Timestamp" < new_floor_ms;

        RAISE NOTICE 'Ротация завершена: удалено месяцев — %. Новая граница ретенции: %.',
            dropped, TO_CHAR(TO_TIMESTAMP(new_floor_ms / 1000.0) AT TIME ZONE 'UTC', 'YYYY-MM');
    END IF;
END;
$$;

-- ============================================================================
--  8. Партиции существующих месяцев + перенос данных
-- ============================================================================

-- Партиции под все месяцы, для которых уже есть партиция Trades.
DO $$
DECLARE
    suffix TEXT;
BEGIN
    FOR suffix IN
        SELECT substring(c.relname FROM 'Trades_(\d{4}_\d{2})')
        FROM pg_inherits i
        JOIN pg_class c ON c.oid = i.inhrelid
        WHERE i.inhparent = 'public."Trades"'::regclass
        ORDER BY 1
    LOOP
        PERFORM public.sp_ensure_month_partitions(
            EXTRACT(EPOCH FROM TO_DATE(suffix, 'YYYY_MM'))::BIGINT * 1000);
    END LOOP;
END $$;

-- Переносим отчёты о качестве. Партиции под их месяцы создаём отдельно:
-- отчёт может относиться к месяцу, партиции Trades под который уже нет.
DO $$
DECLARE
    m DATE;
BEGIN
    FOR m IN SELECT DISTINCT "PeriodMonth" FROM public."DataQualityReports_old" ORDER BY 1 LOOP
        PERFORM public.sp_ensure_month_partitions(
            EXTRACT(EPOCH FROM m)::BIGINT * 1000);
    END LOOP;
END $$;

INSERT INTO public."DataQualityReports"
    ("Id", "Symbol", "PeriodMonth", "TradeCount", "GapCount", "InvalidPriceCount",
     "OutlierCount", "Status", "CheckedAt")
SELECT "Id", "Symbol", "PeriodMonth", "TradeCount", "GapCount", "InvalidPriceCount",
       "OutlierCount", "Status", "CheckedAt"
FROM public."DataQualityReports_old"
WHERE EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'DataQualityReports_' || TO_CHAR("PeriodMonth", 'YYYY_MM')
);

DO $$
DECLARE
    m TIMESTAMPTZ;
BEGIN
    FOR m IN SELECT DISTINCT DATE_TRUNC('month', "PeriodFrom") FROM public."DataQualityFindings_old" ORDER BY 1 LOOP
        PERFORM public.sp_ensure_month_partitions(
            EXTRACT(EPOCH FROM m)::BIGINT * 1000);
    END LOOP;
END $$;

INSERT INTO public."DataQualityFindings"
    ("Id", "CheckGroup", "CheckType", "Symbol", "PeriodFrom", "PeriodTo",
     "Severity", "Count", "Details", "CheckedAt")
SELECT "Id", "CheckGroup", "CheckType", "Symbol", "PeriodFrom", "PeriodTo",
       "Severity", "Count", "Details", "CheckedAt"
FROM public."DataQualityFindings_old"
WHERE EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'DataQualityFindings_' || TO_CHAR("PeriodFrom" AT TIME ZONE 'UTC', 'YYYY_MM')
);

DROP TABLE public."DataQualityReports_old";
DROP TABLE public."DataQualityFindings_old";

-- ============================================================================
--  9. Процедуры, пишущие в свечи и фичи, теперь заводят партицию перед вставкой
-- ============================================================================

CREATE OR REPLACE FUNCTION public.sp_aggregate_trades_to_ohlcv() RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
    start_timestamp BIGINT;
    end_timestamp BIGINT;
    interval BIGINT := 60000;
    month_ms BIGINT;
BEGIN
    -- 1. Получаем "вотермарку" - нашу точку старта
    SELECT "LastProcessedTimestamp" INTO start_timestamp
    FROM public."Processing_Watermarks"
    WHERE "ProcessName" = 'OhlcvAggregator';

    -- 2. Находим время последней НОВОЙ сделки, чтобы определить конец "окна"
    SELECT MAX("TradeTime") INTO end_timestamp
    FROM public."Trades"
    WHERE "ProcessingStatus" = 'new' AND "TradeTime" >= start_timestamp;

    IF end_timestamp IS NULL THEN RETURN; END IF;

    -- 3. Агрегируем только "новые" тики в найденном "окне"
    CREATE TEMP TABLE NewCandles ON COMMIT DROP AS
    WITH Aggregates AS (
        SELECT "Symbol", ("TradeTime" / interval) * interval AS "OpenTime", MIN("Price") AS "LowPrice", MAX("Price") AS "HighPrice",
               SUM("Quantity") AS "Volume", MIN("TradeId") AS "FirstTradeId", MAX("TradeId") AS "LastTradeId"
        FROM public."Trades"
        WHERE "ProcessingStatus" = 'new' AND "TradeTime" >= start_timestamp AND "TradeTime" <= end_timestamp
        GROUP BY 1, 2
    )
    SELECT agg."Symbol", agg."OpenTime", f."Price" AS "OpenPrice", agg."HighPrice", agg."LowPrice", l."Price" AS "ClosePrice", agg."Volume"
    FROM Aggregates agg
    JOIN public."Trades" f ON agg."FirstTradeId" = f."TradeId"
    JOIN public."Trades" l ON agg."LastTradeId" = l."TradeId";

    IF NOT FOUND THEN RETURN; END IF;

    -- 3a. Свечи могут попасть в месяцы, партиций под которые ещё нет.
    FOR month_ms IN SELECT DISTINCT "OpenTime" FROM NewCandles LOOP
        PERFORM public.sp_ensure_month_partitions(month_ms);
    END LOOP;

    -- 4. Вставляем/обновляем свечи
    INSERT INTO public."Ohlcv_1min" ("Symbol", "OpenTime", "OpenPrice", "HighPrice", "LowPrice", "ClosePrice", "Volume")
    SELECT "Symbol", "OpenTime", "OpenPrice", "HighPrice", "LowPrice", "ClosePrice", "Volume" FROM NewCandles
    ON CONFLICT ("Symbol", "OpenTime") DO UPDATE
    SET "HighPrice" = GREATEST(public."Ohlcv_1min"."HighPrice", EXCLUDED."HighPrice"),
        "LowPrice" = LEAST(public."Ohlcv_1min"."LowPrice", EXCLUDED."LowPrice"),
        "ClosePrice" = EXCLUDED."ClosePrice",
        "Volume" = EXCLUDED."Volume";

    -- 5. Помечаем обработанные тики как "processed"
    UPDATE public."Trades"
    SET "ProcessingStatus" = 'processed'
    WHERE "ProcessingStatus" = 'new' AND "TradeTime" >= start_timestamp AND "TradeTime" <= end_timestamp;

    -- 6. Сдвигаем "вотермарку" вперед
    UPDATE public."Processing_Watermarks"
    SET "LastProcessedTimestamp" = end_timestamp
    WHERE "ProcessName" = 'OhlcvAggregator';
END;
$$;

CREATE OR REPLACE FUNCTION public.sp_aggregate_trades_to_ohlcv(p_start_timestamp bigint, p_end_timestamp bigint) RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
    interval_ms BIGINT := 60000;
    m TIMESTAMP;
BEGIN
    -- Окно может пересекать границу месяца — заводим партиции под все затронутые месяцы.
    FOR m IN
        SELECT generate_series(
            DATE_TRUNC('month', TO_TIMESTAMP(p_start_timestamp / 1000.0) AT TIME ZONE 'UTC'),
            DATE_TRUNC('month', TO_TIMESTAMP(p_end_timestamp   / 1000.0) AT TIME ZONE 'UTC'),
            INTERVAL '1 month')
    LOOP
        PERFORM public.sp_ensure_month_partitions(EXTRACT(EPOCH FROM m)::BIGINT * 1000);
    END LOOP;

    WITH TradesInWindow AS (
        SELECT "Symbol", "TradeId", "Price", "Quantity", "TradeTime"
        FROM public."Trades"
        WHERE "ProcessingStatus" = 'new'
          AND "TradeTime" >= p_start_timestamp
          AND "TradeTime" < p_end_timestamp
    ),
    MinuteAggregates AS (
        SELECT
            "Symbol",
            ("TradeTime" / interval_ms) * interval_ms AS "OpenTime",
            MIN("Price") AS "Low",
            MAX("Price") AS "High",
            SUM("Quantity") AS "Vol",
            (array_agg("Price" ORDER BY "TradeTime" ASC, "TradeId" ASC))[1] AS "Open",
            (array_agg("Price" ORDER BY "TradeTime" DESC, "TradeId" DESC))[1] AS "Close"
        FROM TradesInWindow
        GROUP BY "Symbol", "OpenTime"
    )
    INSERT INTO public."Ohlcv_1min" ("Symbol", "OpenTime", "OpenPrice", "HighPrice", "LowPrice", "ClosePrice", "Volume", "ProcessingStatus")
    SELECT
        "Symbol", "OpenTime", "Open", "High", "Low", "Close", "Vol", 'new'
    FROM MinuteAggregates
    ON CONFLICT ("Symbol", "OpenTime") DO UPDATE SET
        "HighPrice" = GREATEST(public."Ohlcv_1min"."HighPrice", EXCLUDED."HighPrice"),
        "LowPrice" = LEAST(public."Ohlcv_1min"."LowPrice", EXCLUDED."LowPrice"),
        "ClosePrice" = EXCLUDED."ClosePrice",
        "Volume" = public."Ohlcv_1min"."Volume" + EXCLUDED."Volume",
        "ProcessingStatus" = 'new';

    UPDATE public."Trades"
    SET "ProcessingStatus" = 'processed'
    WHERE
        "ProcessingStatus" = 'new'
        AND "TradeTime" >= p_start_timestamp
        AND "TradeTime" < p_end_timestamp;
END;
$$;

CREATE OR REPLACE FUNCTION public.sp_upsert_ohlcv_features(p_symbols character varying[], p_open_times bigint[], p_rsi_14 numeric[], p_macd_signals numeric[], p_macd_hists numeric[], p_ma_1051200 numeric[], p_ma_201600 numeric[], p_cvds numeric[]) RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
    month_ms BIGINT;
BEGIN
    CREATE TEMP TABLE NewFeatures ON COMMIT DROP AS
    SELECT * FROM UNNEST(
        p_symbols, p_open_times, p_rsi_14, p_macd_signals, p_macd_hists,
        p_ma_1051200, p_ma_201600, p_cvds
    ) AS t(
        "Symbol", "OpenTime", "RSI_14", "MACD_Signal", "MACD_Hist",
        "MA_1051200", "MA_201600", "CVD"
    );

    FOR month_ms IN SELECT DISTINCT "OpenTime" FROM NewFeatures LOOP
        PERFORM public.sp_ensure_month_partitions(month_ms);
    END LOOP;

    INSERT INTO public."Ohlcv_Features" (
        "Symbol", "OpenTime", "RSI_14", "MACD_Signal", "MACD_Hist",
        "MA_1051200", "MA_201600", "CVD"
    )
    SELECT * FROM NewFeatures
    ON CONFLICT ("Symbol", "OpenTime") DO UPDATE
    SET
        "RSI_14" = EXCLUDED."RSI_14",
        "MACD_Signal" = EXCLUDED."MACD_Signal",
        "MACD_Hist" = EXCLUDED."MACD_Hist",
        "MA_1051200" = EXCLUDED."MA_1051200",
        "MA_201600" = EXCLUDED."MA_201600",
        "CVD" = EXCLUDED."CVD";
END;
$$;

COMMIT;
