<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<CodePage>65001</CodePage>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-BinanceDataCollector.Worker-e1a4dfa0-9271-477a-9fef-2196cb547f2d</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.21" />
		<PackageReference Include="Hangfire.PostgreSql" Version="1.20.12" />
		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
		<PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
		<PackageReference Include="Serilog.Enrichers.WithCaller" Version="1.3.0" />
		<PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
		<PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Workers\Audits\" />
		<Folder Include="Workers\Features\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BinanceDataCollector.Application\BinanceDataCollector.Application.csproj" />
	  <ProjectReference Include="..\BinanceDataCollector.Infrastructure\BinanceDataCollector.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="appsettings.Development.json">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
    
</Project>
