services:
  bdc_db:
    image: postgres:16-alpine
    container_name: bdc_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=market_analytics
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d market_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5

  bdc_pgbouncer:
    image: edoburu/pgbouncer
    container_name: bdc_pgbouncer
    restart: always
    depends_on:
      - bdc_db
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=bdc_db
      - DB_PORT=5432
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=100
      - MIN_POOL_SIZE=10
      - RESERVE_POOL_SIZE=10
      - AUTH_TYPE=scram-sha-256

  bdc_seq:
    image: datalust/seq:latest
    container_name: bdc_seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=${SEQ_ADMIN_USER}
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_ADMIN_PASS}
      - SERILOG_SEQ_URL=${SERILOG_SEQ_URL}
    volumes:
      - bdc_seq_data:/data

  bdc_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: bdc_rabbitmq
    restart: always
    volumes:
      - bdc_rabbitmq_data:/var/lib/rabbitmq/

volumes:
  bdc_seq_data:
  bdc_rabbitmq_data:
  bdc_data: