-- Результаты проверок качества данных, запускаемых вручную оператором
-- со страницы /DataQuality в DataManager.
--
-- Отличие от "DataQualityReports": та таблица хранит один агрегированный отчёт
-- на пару (символ, месяц). Здесь — отдельная запись на каждую сработавшую
-- проверку, с произвольным периодом и деталями в JSONB.
--
-- Применение на существующей БД:
--   psql -U bindatacoll -d market_analytics -f 001_data_quality_findings.sql
-- На чистом томе применяется автоматически из baseline 02_schema.sql.

CREATE TABLE IF NOT EXISTS public."DataQualityFindings" (
    "Id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CheckGroup" character varying(32) NOT NULL,   -- trades | ohlcv | features | pipeline
    "CheckType"  character varying(64) NOT NULL,   -- конкретная проверка внутри группы
    "Symbol"     character varying(20),            -- NULL, если проверка не привязана к символу
    "PeriodFrom" timestamp with time zone NOT NULL,
    "PeriodTo"   timestamp with time zone NOT NULL,
    "Severity"   character varying(10) NOT NULL,   -- ok | warning | error
    "Count"      bigint DEFAULT 0 NOT NULL,        -- сколько записей нарушают проверку
    "Details"    jsonb,                            -- примеры/подробности, зависят от CheckType
    "CheckedAt"  timestamp with time zone DEFAULT now() NOT NULL
);

-- Выборка последних результатов — основной сценарий страницы
CREATE INDEX IF NOT EXISTS ix_dqf_checked_at
    ON public."DataQualityFindings" USING btree ("CheckedAt" DESC);

-- Быстрый доступ к проблемам (страница по умолчанию показывает их)
CREATE INDEX IF NOT EXISTS ix_dqf_severity
    ON public."DataQualityFindings" USING btree ("Severity")
    WHERE ("Severity")::text <> 'ok'::text;

-- Фильтрация по группе проверок и символу
CREATE INDEX IF NOT EXISTS ix_dqf_group_symbol
    ON public."DataQualityFindings" USING btree ("CheckGroup", "Symbol");
