name: Deploy Binance Collector

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }} # Используем github.actor - это всегда работает
        password: ${{ secrets.DOCKОКER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta # Даем этому шагу ID, чтобы ссылаться на его результат
      uses: docker/metadata-action@v5
      with:
        # Собираем имя образа. Оно автоматически будет приведено к нижнему регистру.
        images: ghcr.io/${{ github.repository }}/binance-collector

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        # Используем теги, сгенерированные на шаге 'meta'
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2237
        script: |
          cd /opt/BinanceCollector
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.DOCKER_PASSWORD }}
          # Собираем имя образа здесь вручную, приводя к нижнему регистру
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}/binance-collector" | tr '[:upper:]' '[:lower:]')
          docker pull $IMAGE_NAME:latest
          docker-compose up -d