name: Deploy Binance Collector

on:
  push:
    branches: [ "master" ] # Запускать при пуше в ветку main

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Пайплайн будет работать на виртуальной машине с Ubuntu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # TODO: Раскомментируйте, когда у вас появятся тесты
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: '8.0.x'
    # - name: Run tests
    #   run: dotnet test --verbosity normal

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository.lowercase }}/binance-collector:latest

  deploy:
    needs: build-and-push # Запускать только после успешной сборки
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2237 # Укажите ваш нестандартный порт SSH
        script: |
          cd /opt/BinanceCollector # Переходим в папку с docker-compose.yml на сервере
          docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ghcr.io/${{ github.repository.lowercase }}/binance-collector:latest
          docker-compose up -d